name: uttt production deployment

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    test:
        name: Lint & Test
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest

            - name: Install dependencies
              run: bun install --frozen-lockfile

            - name: Lint
              run: bun run lint

            - name: Test
              run: bun run test

    deploy:
        name: Build & Deploy on Server
        needs: test
        runs-on: [self-hosted, production]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Build and Start Container
              run: |
                  docker compose up -d --build --remove-orphans

            - name: Clean up old build images
              run: |
                  docker image prune -f
